### PR TITLE
Statistics part and rails syntax update

### PR DESCRIPTION
**Pull request by renemadsen**
We where missing the statistics part and in the process updating the syntax to use ' instead of " in the proper placese.

### CODE REVIEW

**Comment by jasonwbarnett** [comment]
Why did you rename these classes?

`Uptrends::Client` -> `UptrendsExtended::Client`
`Uptrends::Base` -> `UptrendsExtended::Base`

**Comment by jasonwbarnett** [comment]
Please remove the `.gitignore` changes from the PR. You should add that to your local machine's global gitignore, it does not belong in the gem's `.gitignore`.

**Comment by jasonwbarnett** [comment]
In general there are too many changes clumped into the same PR. Please split the types of changes into smaller PRs.

Thank you

**Comment by renemadsen** [comment]
We needed the gem in a lot of projects with the stats part, so I had to
publish a new gem and in order for me to do so I had to rename the
gem/classes to not confuse with your gem.

I know the pull request was including a lot of changes.

I'll make another pull request with the changes without the renaming of
classes.

**Comment by jasonwbarnett** [comment]
Thank you.

**Pull request closed without merging**
